name: Deploy API Service

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-api-service:${{ github.sha }} .

      - name: Run basic health check
        run: |
          echo "Running basic health checks..."
          sleep 2
          echo "Health checks passed"

      - name: Deploy to staging
        run: |
          echo "Deploying image my-api-service:${{ github.sha }} to staging..."
          echo "Deployment complete"
